
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MYSLAVE_H
#define MYSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 MySlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * MySlave_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data MySlave_Data;
extern UNS8 Data1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 Data2_Data2_1;		/* Mapped at index 0x2001, subindex 0x01 */
extern UNS8 Data2_Data2_2;		/* Mapped at index 0x2001, subindex 0x02 */
extern UNS8 Data3;		/* Mapped at index 0x2002, subindex 0x00*/
extern INTEGER16 Data4[2];		/* Mapped at index 0x2003, subindex 0x01 - 0x02 */
extern UNS8 Data5;		/* Mapped at index 0x2004, subindex 0x00*/
extern INTEGER32 Data6_Data6_1;		/* Mapped at index 0x2005, subindex 0x01 */
extern INTEGER32 Data6_Data6_2;		/* Mapped at index 0x2005, subindex 0x02 */

#endif // MYSLAVE_H
